name: Jira Issues Clone CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  forge-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Forge CLI
        shell: pwsh
        run: npm install -g @forge/cli

      - name: Authenticate Forge (non-interactive)
        shell: pwsh
        env:
          FORGE_EMAIL: ${{ secrets.FORGE_EMAIL }}
          FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
        run: |
          try { forge logout } catch {}
          forge login --email "$env:FORGE_EMAIL" --token "$env:FORGE_API_TOKEN" --non-interactive

      - name: Install dependencies (if package.json exists)
        shell: pwsh
        run: |
          if (Test-Path package.json) {
            try { npm ci } catch { npm install }
          } else {
            Write-Host "No package.json found. Skipping npm install."
          }

      - name: Forge Lint
        shell: pwsh
        run: |
          try { forge lint } catch { Write-Host "⚠️ Forge lint found issues or warnings; continuing." }

      - name: Forge Deploy (development)
        shell: pwsh
        run: forge deploy --environment development

      - name: Forge Install to Confluence (development)
        shell: pwsh
        run: forge install --product confluence --site petitpain.atlassian.net --environment development --non-interactive --confirm-scopes

      - name: Upload Forge logs (if any)
        uses: actions/upload-artifact@v4
        with:
          name: forge-logs
          path: |
            .forge/**
            **/forge.log
          if-no-files-found: ignore

      - name: Done
        shell: pwsh
        run: echo "✅ Deploy & install completed."
