name: Forge OJMF Automation Agent

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  forge-deploy:
    runs-on: ubuntu-latest
    env:
      # CI auth for Forge CLI (no `forge login` in CI)
      FORGE_EMAIL: ${{ secrets.FORGE_EMAIL }}
      FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js (22.x required by Forge CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Forge CLI
        run: npm install -g @forge/cli@latest

      - name: Disable Forge analytics (non-TTY safe)
        run: forge settings set usage-analytics false

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Forge Lint (non-blocking)
        run: forge lint || echo "lint warnings - proceeding"

      - name: Deploy (development)
        run: forge deploy --environment development --non-interactive

      - name: Install to Confluence (development) — idempotent
        run: |
          set -eo pipefail
          BASE_CMD="forge install --product confluence --site petitpain.atlassian.net --environment development --confirm-scopes --non-interactive"

          echo "Attempting upgrade install..."
          UPG_OUT="$($BASE_CMD --upgrade 2>&1)" || true
          echo "$UPG_OUT"

          if echo "$UPG_OUT" | grep -qi "already installed with id"; then
            echo "App already installed — treating as success."
            exit 0
          fi

          if echo "$UPG_OUT" | grep -qi "Could not find an installation"; then
            echo "No existing install. Trying fresh install..."
            FRESH_OUT="$($BASE_CMD 2>&1)" || true
            echo "$FRESH_OUT"
            if echo "$FRESH_OUT" | grep -qi "already installed with id"; then
              echo "App already installed — treating as success."
              exit 0
            fi
            # if forge returned non-zero and wasn't the benign 'already installed', fail
            if ! echo "$FRESH_OUT" | grep -qi "completed"; then
              echo "forge install failed"; exit 1
            fi
            exit 0
          fi

          # If we get here and the upgrade output didn't error, we're good.
          if echo "$UPG_OUT" | grep -qi "completed"; then
            echo "Upgrade install completed."
            exit 0
          fi

          echo "forge install/upgrade failed unexpectedly"
          exit 1

      - name: Upload Forge logs (if any)
        uses: actions/upload-artifact@v4
        with:
          name: forge-logs
          path: |
            .forge/**
            **/forge.log
          if-no-files-found: ignore
