name: Jira Issues Clone CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '*/20 * * * *'  # optional: auto-deploy every 20 min so Agent Mode can rely on it

permissions:
  contents: write  # allow committing to docs/progress-log.md

concurrency:
  group: deploy-install
  cancel-in-progress: false

jobs:
  forge-deploy:
    runs-on: windows-latest   # << GitHub-hosted runner
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Prepare npm (quiet)
        run: |
          npm config set fund false
          npm config set audit false

      - name: Install Forge CLI
        run: npm install -g @forge/cli

      - name: Authenticate Forge (non-interactive)
        env:
          FORGE_EMAIL: ${{ secrets.FORGE_EMAIL }}
          FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
        run: |
          try { forge logout } catch {}
          forge login --email "$env:FORGE_EMAIL" --token "$env:FORGE_API_TOKEN" --non-interactive

      - name: Install dependencies (ci if lockfile, else install)
        run: |
          if (Test-Path package.json) {
            if (Test-Path package-lock.json) {
              Write-Host "Using npm ci (lockfile present)"
              npm ci
            } else {
              Write-Host "No lockfile found -> npm install"
              npm install
            }
          } else {
            Write-Host "No package.json found. Skipping npm install."
          }

      - name: Forge Lint (non-blocking)
        run: |
          try { forge lint } catch { Write-Host "⚠️ forge lint issues; continuing." }

      - name: Forge Deploy (development)
        run: forge deploy --environment development

      - name: Forge Install to Confluence (development)
        run: forge install --product confluence --site petitpain.atlassian.net --environment development --non-interactive --confirm-scopes

      - name: Append progress log (repo memory for Agent Mode)
        env:
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          $ts = (Get-Date).ToString("s")
          New-Item -ItemType Directory -Force -Path "docs" | Out-Null
          $line = "[$ts] Deploy+Install success on '${{ github.ref }}' via GitHub-hosted runner. Run: $env:RUN_URL"
          if (Test-Path "docs/progress-log.md") {
            Add-Content "docs/progress-log.md" $line
          } else {
            Set-Content "docs/progress-log.md" "# Progress Log`n$line"
          }
          git config user.email "actions@github.com"
          git config user.name "github-actions[bot]"
          git add docs/progress-log.md
          git commit -m "CI: log deploy/install [$ts]" || echo "No changes to commit"
          git push

      - name: Done
        run: echo "✅ Deploy & install completed."
