name: Forge OJMF Automation Agent

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  forge-deploy:
    runs-on: ubuntu-latest
    env:
      FORGE_EMAIL: ${{ secrets.FORGE_EMAIL }}
      FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js (22.x required by Forge CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Forge CLI
        run: npm install -g @forge/cli@latest

      - name: Disable Forge analytics (non-TTY safe)
        run: forge settings set usage-analytics false

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Forge Lint (non-blocking)
        run: forge lint || echo "lint warnings - proceeding"

      - name: Deploy (development)
        run: forge deploy --environment development --non-interactive

      - name: Install to Confluence (development) — idempotent
        run: |
          set -eo pipefail
          BASE_CMD="forge install --product confluence --site petitpain.atlassian.net --environment development --confirm-scopes --non-interactive"

          echo "Attempting upgrade install..."
          set +e
          UPG_OUT=$($BASE_CMD --upgrade 2>&1); UPG_RC=$?
          set -e
          echo "$UPG_OUT"

          # Success cases
          if [ $UPG_RC -eq 0 ] || echo "$UPG_OUT" | grep -qiE "already installed with id|already at the latest version|at the latest"; then
            echo "App installed/up-to-date — OK."
            exit 0
          fi

          # First-time install path
          if echo "$UPG_OUT" | grep -qi "Could not find an installation"; then
            echo "No previous install detected. Trying fresh install..."
            set +e
            FRESH_OUT=$($BASE_CMD 2>&1); FRESH_RC=$?
            set -e
            echo "$FRESH_OUT"
            if [ $FRESH_RC -eq 0 ] || echo "$FRESH_OUT" | grep -qiE "completed|already installed|already at the latest version|at the latest"; then
              echo "Fresh install completed/OK."
              exit 0
            fi
            echo "Fresh install failed"
            exit 1
          fi

          echo "Unexpected install/upgrade failure"
          exit 1

      - name: Upload Forge logs (if any)
        uses: actions/upload-artifact@v4
        with:
          name: forge-logs
          path: |
            .forge/**
            **/forge.log
          if-no-files-found: ignore
