name: Forge OJMF Automation Agent

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  forge-deploy:
    runs-on: ubuntu-latest
    env:
      FORGE_EMAIL: ${{ secrets.FORGE_EMAIL }}
      FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js (22.x)
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Forge CLI
        run: npm install -g @forge/cli

      - name: Disable Forge analytics (non-TTY safe)
        run: forge settings set usage-analytics false

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Forge Lint (non-blocking)
        run: forge lint || echo "lint warnings - proceeding"

      - name: Deploy (development)
        run: forge deploy --environment development --non-interactive

      - name: Install to Confluence (development)
        run: >
          forge install
          --product confluence
          --site petitpain.atlassian.net
          --environment development
          --confirm-scopes
          --non-interactive
          --upgrade

      - name: Upload Forge logs (if any)
        uses: actions/upload-artifact@v4
        with:
          name: forge-logs
          path: |
            .forge/**
            **/forge.log
          if-no-files-found: ignore
